name = "Luxor"
uuid = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
authors = ["cormullion <cormullion@mac.com>"]
version = "1.6.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
