name = "Luxor"
uuid = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
authors = ["cormullion <cormullion@mac.com>"]
version = "3.3.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rsvg = "c4c386cf-5103-5370-be45-f3a111cca3b8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
Cairo = "0.7, 0.8, 1.0"
Colors = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 1.0"
FFMPEG = "0.4"
FileIO = "1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13"
Juno = "0.7, 0.8"
Rsvg = "1.0"
Requires = "1"
LaTeXStrings = "1.1, 1.2, 1.3"
julia = "1.6"

[extras]
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[targets]
test = ["ImageIO", "Test", "MathTeXEngine", "LaTeXStrings"]
