[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Typstry = "f0ed7684-a786-439e-b1e3-3b82803b501e"

[compat]
Colors = "0.12, 0.13"
Documenter = "1"
MathTeXEngine = "0.6"
Typstry = "0.6"
